INSERT INTO cabos (norma_abnt, tipo_cabo, tensao_isolamento, material_isolacao, material_cobertura, temp_max_operacao_c, temp_max_sobrecarga_c, temp_max_curto_circuito, numero_condutores) VALUES
    ('NBR NM 247-3', 'Superastic',    '450/750 V', 'PVC',    NULL,   70, 100, '140 / 160*', '1'),
    ('NBR NM 247-3', 'Superastic Flex','450/750 V','PVC',    NULL,   70, 100, '140 / 160*', '1'),
    ('NBR 13248',    'Afumex Green',  '450/750 V', 'LSHF/A', NULL,   70, 100, '160',        '1'),
    ('NBR 7288',     'Sintenax',      '0,6/1 kV',  'PVC',    'PVC',  70, 100, '140 / 160*', '1,2,3,4 e 5'),
    ('NBR 7288',     'Sintenax Flex', '0,6/1 kV',  'PVC',    'PVC',  70, 100, '140 / 160*', '1,2,3,4 e 5'),
    ('NBR 7286',     'GSette Easy',   '0,6/1 kV',  'HEPR',   'PVC',  90, 130, '250',        '1,2,3,4 e 5'),
    ('NBR 7285',     'Voltalene',     '0,6/1 kV',  'XLPE',   NULL,   90, 130, '250',        '1 ou 3 (triplexado)'),
    ('NBR 7287',     'Voltenax',      '0,6/1 kV',  'XLPE',   'PVC',  90, 130, '250',        '1,2,3,4 e 5'),
    ('NBR 13248',    'Afumex Flex',   '0,6/1 kV',  'HEPR',   'SHF1', 90, 130, '250',        '1,2,3,4 e 5');

INSERT INTO metodo_instalacao (tipo_linha_eletrica, numero_metodo, ref_condutor_isolado, ref_cabo_unipolar, ref_cabo_multipolar) VALUES
    ('Eletroduto embutido em parede isolante',                                          '1/2',                  'A1',  'A1',  'A2'),
    ('Embutimento direto em parede isolante',                                           '51',                   NULL,  NULL,  'A1'),
    ('Moldura',                                                                         '71',                   'A1',  'A1',  NULL),
    ('Eletroduto embutido em caixilho de porta ou janela',                              '73/74',                'A1',  NULL,  NULL),
    ('Embutimento direto em caixilho de porta ou janela',                               '73/74',                NULL,  'A1',  'A1'),
    ('Eletroduto aparente',                                                             '3/4/5/6',              'B1',  'B1',  'B2'),
    ('Eletroduto embutido em alvenaria',                                                '7/8',                  'B1',  'B1',  'B2'),
    ('Diretamente em espaço de construção - 1,5De ≤ V < 5De',                          '21',                   NULL,  'B2',  'B2'),
    ('Diretamente em espaço de construção - 5De ≤ V < 50De',                           '21',                   NULL,  'B1',  'B1'),
    ('Eletroduto em espaço de construção - 1,5De ≤ V < 5De',                           '22/24',                'B2',  NULL,  NULL),
    ('Eletroduto em espaço de construção - V ≥ 20De',                                  '22/24',                'B1',  NULL,  NULL),
    ('Eletroduto em espaço de construção',                                              '23/25',                NULL,  'B2',  'B2'),
    ('Eletroduto de seção não circular embutido em alvenaria - 1,5De ≤ V < 5De',       '26',                   'B2',  NULL,  NULL),
    ('Eletroduto de seção não circular embutido em alvenaria - 5De ≤ V < 50De',        '26',                   'B1',  NULL,  NULL),
    ('Eletroduto de seção não circular embutido em alvenaria',                          '27',                   NULL,  'B2',  'B2'),
    ('Forro falso ou piso elevado - 1,5De ≤ V < 5De',                                  '28',                   NULL,  'B2',  'B2'),
    ('Forro falso ou piso elevado - 5De ≤ V < 50De',                                   '28',                   NULL,  'B1',  'B1'),
    ('Eletrocalha',                                                                     '31/31A/32/32A/35/36',  'B1',  'B1',  'B2'),
    ('Canaleta fechada no piso, solo ou parede',                                        '33/34/72/72A/75/75A',  'B1',  'B1',  'B2'),
    ('Eletroduto em canaleta fechada - 1,5De ≤ V < 20De',                              '41',                   'B2',  'B2',  NULL),
    ('Eletroduto em canaleta fechada - V ≥ 20De',                                      '41',                   'B1',  'B1',  NULL),
    ('Eletroduto em canaleta ventilada no piso ou solo',                                '42',                   'B1',  NULL,  NULL),
    ('Canaleta ventilada no piso ou solo',                                              '43',                   NULL,  'B1',  'B1'),
    ('Fixação direta à parede ou teto',                                                 '11/11A/11B',           NULL,  'C',   'C'),
    ('Bandejas não perfuradas ou prateleiras',                                          '12',                   NULL,  'C',   'C'),
    ('Embutimento direto em alvenaria',                                                 '52/53',                NULL,  'C',   'C'),
    ('Eletroduto enterrado no solo ou canaleta não ventilada no solo',                  '61/61A',               NULL,  'D',   'D'),
    ('Diretamente enterrado',                                                           '63',                   NULL,  'D',   'D'),
    ('Bandejas perfuradas (horizontal ou vertical)',                                    '13',                   NULL,  'F',   'E'),
    ('Leitos, suportes horizontais ou telas',                                           '14/16',                NULL,  'F',   'E'),
    ('Afastado da parede ou suspenso por cabo de suporte',                              '15/17',                NULL,  'F',   'E'),
    ('Sobre isoladores',                                                                '18',                   'G',   'G',   NULL);

-- ============================================================
-- cabos_metodo_instalacao
-- Pairs resolved by name via JOIN — no hardcoded IDs.
-- ============================================================
INSERT INTO cabos_metodo_instalacao (cabos_id, metodo_instalacao_id)
SELECT c.id, m.id
FROM (VALUES
    -- Condutor Isolado: Superastic, Superastic Flex, Afumex Green
    ('Superastic',      'Eletroduto embutido em parede isolante'),
    ('Superastic',      'Moldura'),
    ('Superastic',      'Eletroduto embutido em caixilho de porta ou janela'),
    ('Superastic',      'Eletroduto aparente'),
    ('Superastic',      'Eletroduto embutido em alvenaria'),
    ('Superastic',      'Eletroduto em espaço de construção - 1,5De ≤ V < 5De'),
    ('Superastic',      'Eletroduto em espaço de construção - V ≥ 20De'),
    ('Superastic',      'Eletroduto de seção não circular embutido em alvenaria - 1,5De ≤ V < 5De'),
    ('Superastic',      'Eletroduto de seção não circular embutido em alvenaria - 5De ≤ V < 50De'),
    ('Superastic',      'Eletrocalha'),
    ('Superastic',      'Canaleta fechada no piso, solo ou parede'),
    ('Superastic',      'Eletroduto em canaleta fechada - 1,5De ≤ V < 20De'),
    ('Superastic',      'Eletroduto em canaleta fechada - V ≥ 20De'),
    ('Superastic',      'Eletroduto em canaleta ventilada no piso ou solo'),
    ('Superastic',      'Sobre isoladores'),

    ('Superastic Flex', 'Eletroduto embutido em parede isolante'),
    ('Superastic Flex', 'Moldura'),
    ('Superastic Flex', 'Eletroduto embutido em caixilho de porta ou janela'),
    ('Superastic Flex', 'Eletroduto aparente'),
    ('Superastic Flex', 'Eletroduto embutido em alvenaria'),
    ('Superastic Flex', 'Eletroduto em espaço de construção - 1,5De ≤ V < 5De'),
    ('Superastic Flex', 'Eletroduto em espaço de construção - V ≥ 20De'),
    ('Superastic Flex', 'Eletroduto de seção não circular embutido em alvenaria - 1,5De ≤ V < 5De'),
    ('Superastic Flex', 'Eletroduto de seção não circular embutido em alvenaria - 5De ≤ V < 50De'),
    ('Superastic Flex', 'Eletrocalha'),
    ('Superastic Flex', 'Canaleta fechada no piso, solo ou parede'),
    ('Superastic Flex', 'Eletroduto em canaleta fechada - 1,5De ≤ V < 20De'),
    ('Superastic Flex', 'Eletroduto em canaleta fechada - V ≥ 20De'),
    ('Superastic Flex', 'Eletroduto em canaleta ventilada no piso ou solo'),
    ('Superastic Flex', 'Sobre isoladores'),

    ('Afumex Green',    'Eletroduto embutido em parede isolante'),
    ('Afumex Green',    'Moldura'),
    ('Afumex Green',    'Eletroduto embutido em caixilho de porta ou janela'),
    ('Afumex Green',    'Eletroduto aparente'),
    ('Afumex Green',    'Eletroduto embutido em alvenaria'),
    ('Afumex Green',    'Eletroduto em espaço de construção - 1,5De ≤ V < 5De'),
    ('Afumex Green',    'Eletroduto em espaço de construção - V ≥ 20De'),
    ('Afumex Green',    'Eletroduto de seção não circular embutido em alvenaria - 1,5De ≤ V < 5De'),
    ('Afumex Green',    'Eletroduto de seção não circular embutido em alvenaria - 5De ≤ V < 50De'),
    ('Afumex Green',    'Eletrocalha'),
    ('Afumex Green',    'Canaleta fechada no piso, solo ou parede'),
    ('Afumex Green',    'Eletroduto em canaleta fechada - 1,5De ≤ V < 20De'),
    ('Afumex Green',    'Eletroduto em canaleta fechada - V ≥ 20De'),
    ('Afumex Green',    'Eletroduto em canaleta ventilada no piso ou solo'),
    ('Afumex Green',    'Sobre isoladores'),

    -- Cabo Unipolar / Multipolar: Sintenax, Sintenax Flex, GSette Easy, Voltalene, Voltenax, Afumex Flex
    ('Sintenax',        'Eletroduto embutido em parede isolante'),
    ('Sintenax',        'Embutimento direto em parede isolante'),
    ('Sintenax',        'Moldura'),
    ('Sintenax',        'Embutimento direto em caixilho de porta ou janela'),
    ('Sintenax',        'Eletroduto aparente'),
    ('Sintenax',        'Eletroduto embutido em alvenaria'),
    ('Sintenax',        'Diretamente em espaço de construção - 1,5De ≤ V < 5De'),
    ('Sintenax',        'Diretamente em espaço de construção - 5De ≤ V < 50De'),
    ('Sintenax',        'Eletroduto em espaço de construção'),
    ('Sintenax',        'Eletroduto de seção não circular embutido em alvenaria'),
    ('Sintenax',        'Forro falso ou piso elevado - 1,5De ≤ V < 5De'),
    ('Sintenax',        'Forro falso ou piso elevado - 5De ≤ V < 50De'),
    ('Sintenax',        'Eletrocalha'),
    ('Sintenax',        'Canaleta fechada no piso, solo ou parede'),
    ('Sintenax',        'Eletroduto em canaleta fechada - 1,5De ≤ V < 20De'),
    ('Sintenax',        'Eletroduto em canaleta fechada - V ≥ 20De'),
    ('Sintenax',        'Canaleta ventilada no piso ou solo'),
    ('Sintenax',        'Fixação direta à parede ou teto'),
    ('Sintenax',        'Bandejas não perfuradas ou prateleiras'),
    ('Sintenax',        'Embutimento direto em alvenaria'),
    ('Sintenax',        'Eletroduto enterrado no solo ou canaleta não ventilada no solo'),
    ('Sintenax',        'Diretamente enterrado'),
    ('Sintenax',        'Bandejas perfuradas (horizontal ou vertical)'),
    ('Sintenax',        'Leitos, suportes horizontais ou telas'),
    ('Sintenax',        'Afastado da parede ou suspenso por cabo de suporte'),
    ('Sintenax',        'Sobre isoladores'),

    ('Sintenax Flex',   'Eletroduto embutido em parede isolante'),
    ('Sintenax Flex',   'Embutimento direto em parede isolante'),
    ('Sintenax Flex',   'Moldura'),
    ('Sintenax Flex',   'Embutimento direto em caixilho de porta ou janela'),
    ('Sintenax Flex',   'Eletroduto aparente'),
    ('Sintenax Flex',   'Eletroduto embutido em alvenaria'),
    ('Sintenax Flex',   'Diretamente em espaço de construção - 1,5De ≤ V < 5De'),
    ('Sintenax Flex',   'Diretamente em espaço de construção - 5De ≤ V < 50De'),
    ('Sintenax Flex',   'Eletroduto em espaço de construção'),
    ('Sintenax Flex',   'Eletroduto de seção não circular embutido em alvenaria'),
    ('Sintenax Flex',   'Forro falso ou piso elevado - 1,5De ≤ V < 5De'),
    ('Sintenax Flex',   'Forro falso ou piso elevado - 5De ≤ V < 50De'),
    ('Sintenax Flex',   'Eletrocalha'),
    ('Sintenax Flex',   'Canaleta fechada no piso, solo ou parede'),
    ('Sintenax Flex',   'Eletroduto em canaleta fechada - 1,5De ≤ V < 20De'),
    ('Sintenax Flex',   'Eletroduto em canaleta fechada - V ≥ 20De'),
    ('Sintenax Flex',   'Canaleta ventilada no piso ou solo'),
    ('Sintenax Flex',   'Fixação direta à parede ou teto'),
    ('Sintenax Flex',   'Bandejas não perfuradas ou prateleiras'),
    ('Sintenax Flex',   'Embutimento direto em alvenaria'),
    ('Sintenax Flex',   'Eletroduto enterrado no solo ou canaleta não ventilada no solo'),
    ('Sintenax Flex',   'Diretamente enterrado'),
    ('Sintenax Flex',   'Bandejas perfuradas (horizontal ou vertical)'),
    ('Sintenax Flex',   'Leitos, suportes horizontais ou telas'),
    ('Sintenax Flex',   'Afastado da parede ou suspenso por cabo de suporte'),
    ('Sintenax Flex',   'Sobre isoladores'),

    ('GSette Easy',     'Eletroduto embutido em parede isolante'),
    ('GSette Easy',     'Embutimento direto em parede isolante'),
    ('GSette Easy',     'Moldura'),
    ('GSette Easy',     'Embutimento direto em caixilho de porta ou janela'),
    ('GSette Easy',     'Eletroduto aparente'),
    ('GSette Easy',     'Eletroduto embutido em alvenaria'),
    ('GSette Easy',     'Diretamente em espaço de construção - 1,5De ≤ V < 5De'),
    ('GSette Easy',     'Diretamente em espaço de construção - 5De ≤ V < 50De'),
    ('GSette Easy',     'Eletroduto em espaço de construção'),
    ('GSette Easy',     'Eletroduto de seção não circular embutido em alvenaria'),
    ('GSette Easy',     'Forro falso ou piso elevado - 1,5De ≤ V < 5De'),
    ('GSette Easy',     'Forro falso ou piso elevado - 5De ≤ V < 50De'),
    ('GSette Easy',     'Eletrocalha'),
    ('GSette Easy',     'Canaleta fechada no piso, solo ou parede'),
    ('GSette Easy',     'Eletroduto em canaleta fechada - 1,5De ≤ V < 20De'),
    ('GSette Easy',     'Eletroduto em canaleta fechada - V ≥ 20De'),
    ('GSette Easy',     'Canaleta ventilada no piso ou solo'),
    ('GSette Easy',     'Fixação direta à parede ou teto'),
    ('GSette Easy',     'Bandejas não perfuradas ou prateleiras'),
    ('GSette Easy',     'Embutimento direto em alvenaria'),
    ('GSette Easy',     'Eletroduto enterrado no solo ou canaleta não ventilada no solo'),
    ('GSette Easy',     'Diretamente enterrado'),
    ('GSette Easy',     'Bandejas perfuradas (horizontal ou vertical)'),
    ('GSette Easy',     'Leitos, suportes horizontais ou telas'),
    ('GSette Easy',     'Afastado da parede ou suspenso por cabo de suporte'),
    ('GSette Easy',     'Sobre isoladores'),

    ('Voltalene',       'Eletroduto embutido em parede isolante'),
    ('Voltalene',       'Embutimento direto em parede isolante'),
    ('Voltalene',       'Moldura'),
    ('Voltalene',       'Embutimento direto em caixilho de porta ou janela'),
    ('Voltalene',       'Eletroduto aparente'),
    ('Voltalene',       'Eletroduto embutido em alvenaria'),
    ('Voltalene',       'Diretamente em espaço de construção - 1,5De ≤ V < 5De'),
    ('Voltalene',       'Diretamente em espaço de construção - 5De ≤ V < 50De'),
    ('Voltalene',       'Eletroduto em espaço de construção'),
    ('Voltalene',       'Eletroduto de seção não circular embutido em alvenaria'),
    ('Voltalene',       'Forro falso ou piso elevado - 1,5De ≤ V < 5De'),
    ('Voltalene',       'Forro falso ou piso elevado - 5De ≤ V < 50De'),
    ('Voltalene',       'Eletrocalha'),
    ('Voltalene',       'Canaleta fechada no piso, solo ou parede'),
    ('Voltalene',       'Eletroduto em canaleta fechada - 1,5De ≤ V < 20De'),
    ('Voltalene',       'Eletroduto em canaleta fechada - V ≥ 20De'),
    ('Voltalene',       'Canaleta ventilada no piso ou solo'),
    ('Voltalene',       'Fixação direta à parede ou teto'),
    ('Voltalene',       'Bandejas não perfuradas ou prateleiras'),
    ('Voltalene',       'Embutimento direto em alvenaria'),
    ('Voltalene',       'Eletroduto enterrado no solo ou canaleta não ventilada no solo'),
    ('Voltalene',       'Diretamente enterrado'),
    ('Voltalene',       'Bandejas perfuradas (horizontal ou vertical)'),
    ('Voltalene',       'Leitos, suportes horizontais ou telas'),
    ('Voltalene',       'Afastado da parede ou suspenso por cabo de suporte'),
    ('Voltalene',       'Sobre isoladores'),

    ('Voltenax',        'Eletroduto embutido em parede isolante'),
    ('Voltenax',        'Embutimento direto em parede isolante'),
    ('Voltenax',        'Moldura'),
    ('Voltenax',        'Embutimento direto em caixilho de porta ou janela'),
    ('Voltenax',        'Eletroduto aparente'),
    ('Voltenax',        'Eletroduto embutido em alvenaria'),
    ('Voltenax',        'Diretamente em espaço de construção - 1,5De ≤ V < 5De'),
    ('Voltenax',        'Diretamente em espaço de construção - 5De ≤ V < 50De'),
    ('Voltenax',        'Eletroduto em espaço de construção'),
    ('Voltenax',        'Eletroduto de seção não circular embutido em alvenaria'),
    ('Voltenax',        'Forro falso ou piso elevado - 1,5De ≤ V < 5De'),
    ('Voltenax',        'Forro falso ou piso elevado - 5De ≤ V < 50De'),
    ('Voltenax',        'Eletrocalha'),
    ('Voltenax',        'Canaleta fechada no piso, solo ou parede'),
    ('Voltenax',        'Eletroduto em canaleta fechada - 1,5De ≤ V < 20De'),
    ('Voltenax',        'Eletroduto em canaleta fechada - V ≥ 20De'),
    ('Voltenax',        'Canaleta ventilada no piso ou solo'),
    ('Voltenax',        'Fixação direta à parede ou teto'),
    ('Voltenax',        'Bandejas não perfuradas ou prateleiras'),
    ('Voltenax',        'Embutimento direto em alvenaria'),
    ('Voltenax',        'Eletroduto enterrado no solo ou canaleta não ventilada no solo'),
    ('Voltenax',        'Diretamente enterrado'),
    ('Voltenax',        'Bandejas perfuradas (horizontal ou vertical)'),
    ('Voltenax',        'Leitos, suportes horizontais ou telas'),
    ('Voltenax',        'Afastado da parede ou suspenso por cabo de suporte'),
    ('Voltenax',        'Sobre isoladores'),

    ('Afumex Flex',     'Eletroduto embutido em parede isolante'),
    ('Afumex Flex',     'Embutimento direto em parede isolante'),
    ('Afumex Flex',     'Moldura'),
    ('Afumex Flex',     'Embutimento direto em caixilho de porta ou janela'),
    ('Afumex Flex',     'Eletroduto aparente'),
    ('Afumex Flex',     'Eletroduto embutido em alvenaria'),
    ('Afumex Flex',     'Diretamente em espaço de construção - 1,5De ≤ V < 5De'),
    ('Afumex Flex',     'Diretamente em espaço de construção - 5De ≤ V < 50De'),
    ('Afumex Flex',     'Eletroduto em espaço de construção'),
    ('Afumex Flex',     'Eletroduto de seção não circular embutido em alvenaria'),
    ('Afumex Flex',     'Forro falso ou piso elevado - 1,5De ≤ V < 5De'),
    ('Afumex Flex',     'Forro falso ou piso elevado - 5De ≤ V < 50De'),
    ('Afumex Flex',     'Eletrocalha'),
    ('Afumex Flex',     'Canaleta fechada no piso, solo ou parede'),
    ('Afumex Flex',     'Eletroduto em canaleta fechada - 1,5De ≤ V < 20De'),
    ('Afumex Flex',     'Eletroduto em canaleta fechada - V ≥ 20De'),
    ('Afumex Flex',     'Canaleta ventilada no piso ou solo'),
    ('Afumex Flex',     'Fixação direta à parede ou teto'),
    ('Afumex Flex',     'Bandejas não perfuradas ou prateleiras'),
    ('Afumex Flex',     'Embutimento direto em alvenaria'),
    ('Afumex Flex',     'Eletroduto enterrado no solo ou canaleta não ventilada no solo'),
    ('Afumex Flex',     'Diretamente enterrado'),
    ('Afumex Flex',     'Bandejas perfuradas (horizontal ou vertical)'),
    ('Afumex Flex',     'Leitos, suportes horizontais ou telas'),
    ('Afumex Flex',     'Afastado da parede ou suspenso por cabo de suporte'),
    ('Afumex Flex',     'Sobre isoladores')
) AS pairs(tipo_cabo, tipo_linha_eletrica)
JOIN cabos c ON c.tipo_cabo = pairs.tipo_cabo
JOIN metodo_instalacao m ON m.tipo_linha_eletrica = pairs.tipo_linha_eletrica;

